version: "2"
services:
  webapp:
    build:
      context: ./flask/
      dockerfile: Dockerfile
    ports:
      - "8000:5000"
    env_file: 
      - ./.env
    depends_on:
      - mysqldb
    networks:
      - my-bridge1
    volumes:
      - "./flask/flask-data:/usr/src"
  mysqldb:
    build:
      context: ./mysql/
      dockerfile: Dockerfile
    env_file:
      - ./.env
    networks:
      - my-bridge1
    volumes:
      - "./mysql/db-data:/var/lib/mysql"


networks:
  my-bridge1:
    driver: bridge
