version: 2
jobs:
  build:
    docker:
      - image: docker:dind
    steps:
      - checkout
      - run: pwd
      - run:
          name: listing contents
          command: |
            ls
            docker build --file ./flask/Dockerfile --tag flask-app:stable .
            docker build --file ./mysql/Dockerfile --tag flask-mysql:stable .


