version: 2.1
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: pwd
      - run:
          name: listing contents
          command: |
            ls
            cd flask/ && docker build --file ./flask/Dockerfile --tag flask-app:stable .
            cd ../mysql && docker build --file ./mysql/Dockerfile --tag flask-mysql:stable .
            docker network create --attachable --driver bridge my-net
            docker run -dt flask-mysql:stable --hostname=mysqldb --name flask-mysql --network my-net
            docker run -dt flask-app:stable --hostname=flask-app --name flask-app -p 8080:5000 --network my-net
            curl http://127.0.0.1:8080

