version: 2.1
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: pwd
      - run:
          name: listing contents
          command: |
            ls
            cd flask/ && docker build --file ./Dockerfile --tag flask-app:stable .
            cd ../mysql && docker build --file ./Dockerfile --tag flask-mysql:stable .
      - run: docker network create --attachable --driver bridge my-net
      - run: docker run -d --hostname mysqldb --name flask-mysql --network my-net flask-mysql:stable
      - run: docker run -d --hostname flask-app --name flask-app -p 8080:5000 --network my-net flask-app:stable
      - run: docker ps -a
      - run: curl "http://127.0.0.1:8080"

