version: 2.1
jobs:
  build:
    docker:
      - image: circleci/golang:1.13-alpine
    steps:
      - checkout
      # ... steps for building/testing app ...

      - setup_remote_docker:
          docker_layer_caching: true
      - run: pwd
      - run:
          name: listing contents
          command: |
            ls
            docker build --file ./flask/Dockerfile --tag flask-app:stable .
            docker build --file ./mysql/Dockerfile --tag flask-mysql:stable .


